language: node_js

node_js:
  - "4.1"

install:
  - npm install

before_script:
  - npm install -g bower

script:
  - gulp lint checkstyle build test

after_success:
  - gulp coverage
  - gulp coveralls
